# -*- coding: utf-8 -*-
"""PhoneNumbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PTznHARHhTF31fGdfgmFh1v0xECDHXw9
"""

pip install phonenumbers

import phonenumbers

from phonenumbers import carrier,geocoder,timezone

mobileNo=input("Enter Mobile No with its country code: ")
mobileNo= phonenumbers.parse(mobileNo)
print("Time Zone for given number is: ",timezone.time_zones_for_number(mobileNo))
print("Country of the given number is: ",geocoder.description_for_number(mobileNo,"en"))
print("Valid Mobile Number is: ",phonenumbers.is_valid_number(mobileNo))
print("Operator Name: ",carrier.name_for_number(mobileNo,'en'))

